version: 2.1

orbs:
  android: circleci/android@0.2.1

jobs:
  build:
    executor: android/android

    steps:
      - checkout
      - run:
          command: ./gradlew assembleDebug
      - attach_workspace:
          at: ./app/build/outputs/debug/apk/app-debug.apk
      - run:
          name: "Publish Release on GitHub"
          command: |
            VERSION="test-ci"
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./app/build/outputs/debug/apk/app-debug.apk

